#!/usr/bin/env python3
"""Build script for {a}OS Explorer concept pages and runtime shim.

Reads data/concepts.json (canonical source of truth) and generates:
  1. data/concepts.generated.js  — window.AOS_CONCEPTS + ALIAS_INDEX
  2. concepts/<slug>.html        — one static page per concept
"""

import json
import os
import sys
import html as html_mod

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT_DIR = os.path.dirname(SCRIPT_DIR)
CONCEPTS_JSON = os.path.join(ROOT_DIR, "data", "concepts.json")
GENERATED_JS = os.path.join(ROOT_DIR, "data", "concepts.generated.js")
CONCEPTS_DIR = os.path.join(ROOT_DIR, "concepts")


def load_concepts():
    with open(CONCEPTS_JSON, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data["concepts"]


def validate(concepts):
    slugs = set()
    aliases_seen = {}
    errors = []

    for c in concepts:
        slug = c["slug"]
        if slug in slugs:
            errors.append(f"Duplicate slug: {slug}")
        slugs.add(slug)

        for alias in c.get("aliases", []):
            key = alias.lower().strip()
            if key in aliases_seen and aliases_seen[key] != slug:
                errors.append(
                    f"Alias collision: '{alias}' maps to both "
                    f"'{aliases_seen[key]}' and '{slug}'"
                )
            aliases_seen[key] = slug

    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)


def generate_js(concepts):
    by_slug = {}
    alias_index = {}

    for c in concepts:
        slug = c["slug"]
        by_slug[slug] = c
        for alias in c.get("aliases", []):
            alias_index[alias.lower().strip()] = slug

    js_lines = [
        "// AUTO-GENERATED by scripts/build_concepts.py — do not edit",
        "// Source of truth: data/concepts.json",
        "(function () {",
        f"  var concepts = {json.dumps(by_slug, indent=2)};",
        f"  var aliasIndex = {json.dumps(alias_index, indent=2)};",
        "  window.AOS_CONCEPTS = concepts;",
        "  window.AOS_ALIAS_INDEX = aliasIndex;",
        "})();",
    ]

    os.makedirs(os.path.dirname(GENERATED_JS), exist_ok=True)
    with open(GENERATED_JS, "w", encoding="utf-8") as f:
        f.write("\n".join(js_lines) + "\n")
    print(f"  ✓ Generated {os.path.relpath(GENERATED_JS, ROOT_DIR)}")


def _esc(text):
    return html_mod.escape(str(text)) if text else ""


def generate_concept_page(concept):
    slug = concept["slug"]
    name = _esc(concept["name"])
    short_def = _esc(concept["shortDefinition"])
    explainer = _esc(concept["explainer"])
    strata = ", ".join(concept.get("strata", []))
    axes = ", ".join(concept.get("axes", []))

    products_html = ""
    for pid in concept.get("relatedProductIds", []):
        products_html += f"      <li><code>{_esc(pid)}</code></li>\n"

    related_html = ""
    for rs in concept.get("relatedConceptSlugs", []):
        related_html += (
            f'      <li><a href="{_esc(rs)}.html">{_esc(rs)}</a>'
            f' · <a href="../explorer.html#concept={_esc(rs)}"'
            f' style="font-size:0.85em;opacity:0.7">'
            f"preview in explorer →</a></li>\n"
        )

    anti_html = ""
    for ap in concept.get("antiPatterns", []):
        anti_html += f"      <li>{_esc(ap)}</li>\n"

    mit_html = ""
    for m in concept.get("mitigations", []):
        mit_html += f"      <li>{_esc(m)}</li>\n"

    sources_html = ""
    for src in concept.get("sources", []):
        href = _esc(src.get("href", "#"))
        label = _esc(src.get("label", href))
        sources_html += f'      <li><a href="../{href}">{label}</a></li>\n'

    # Always add the explorer deep-link as a source
    sources_html += (
        f'      <li><a href="../explorer.html#concept={_esc(slug)}">'
        f"Open in Explorer →</a></li>\n"
    )

    page = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{{a}}OS Concept — {name}</title>
  <style>
    :root {{
      --bg: #0f0f14;
      --bg-surface: #1a1a24;
      --text-primary: #e8e8f0;
      --text-secondary: #a0a0b8;
      --text-tertiary: #6b6b80;
      --accent-indigo: #818cf8;
      --border: rgba(255,255,255,0.08);
      --danger: #f87171;
      --success: #34d399;
    }}
    * {{ margin: 0; padding: 0; box-sizing: border-box; }}
    body {{
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: var(--bg);
      color: var(--text-primary);
      line-height: 1.6;
      padding: 2rem;
      max-width: 740px;
      margin: 0 auto;
    }}
    a {{ color: var(--accent-indigo); text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    h1 {{ font-size: 1.8rem; margin-bottom: 0.3rem; }}
    .slug {{ font-size: 0.85rem; color: var(--text-tertiary); margin-bottom: 1.2rem; }}
    .short-def {{ font-size: 1.05rem; color: var(--text-secondary); margin-bottom: 1.5rem; border-left: 3px solid var(--accent-indigo); padding-left: 12px; }}
    section {{ margin-bottom: 1.5rem; }}
    section h2 {{ font-size: 1rem; text-transform: uppercase; letter-spacing: 1px; color: var(--text-tertiary); margin-bottom: 0.5rem; }}
    section p {{ color: var(--text-secondary); }}
    .meta {{ display: flex; gap: 1.5rem; flex-wrap: wrap; margin-bottom: 1.5rem; }}
    .meta span {{ font-size: 0.85rem; color: var(--text-tertiary); }}
    .meta strong {{ color: var(--text-primary); }}
    ul {{ padding-left: 1.2rem; color: var(--text-secondary); }}
    li {{ margin-bottom: 0.4rem; }}
    code {{ background: var(--bg-surface); padding: 2px 6px; border-radius: 4px; font-size: 0.9em; }}
    .callout {{ padding: 10px 14px; border-radius: 8px; margin-bottom: 0.8rem; font-size: 0.92rem; line-height: 1.5; }}
    .callout-danger {{ background: rgba(248,113,113,0.08); border-left: 3px solid var(--danger); color: var(--text-secondary); }}
    .callout-success {{ background: rgba(52,211,153,0.08); border-left: 3px solid var(--success); color: var(--text-secondary); }}
    .back {{ display: inline-block; margin-bottom: 1.5rem; font-size: 0.9rem; }}
    .nav-footer {{ margin-top: 2rem; padding-top: 1rem; border-top: 1px solid var(--border); font-size: 0.85rem; color: var(--text-tertiary); }}
  </style>
</head>
<body>
  <a class="back" href="../explorer.html#concept={_esc(slug)}">← Back to Explorer</a>

  <h1>{name}</h1>
  <div class="slug">/{_esc(slug)}</div>
  <div class="short-def">{short_def}</div>

  <div class="meta">
    <span>Strata: <strong>{_esc(strata)}</strong></span>
    <span>Axes: <strong>{_esc(axes)}</strong></span>
    <span>Status: <strong>{_esc(concept.get("status", "seed"))}</strong></span>
  </div>

  <section>
    <h2>Explainer</h2>
    <p>{explainer}</p>
  </section>

  <section>
    <h2>Anti-Patterns</h2>
{("    <ul>\n" + anti_html.rstrip() + "\n    </ul>") if anti_html else "    <p>None documented yet.</p>"}
  </section>

  <section>
    <h2>Mitigations</h2>
{("    <ul>\n" + mit_html.rstrip() + "\n    </ul>") if mit_html else "    <p>None documented yet.</p>"}
  </section>

  <section>
    <h2>Top Products</h2>
    <ul>
{products_html.rstrip() if products_html else "      <li>None mapped yet.</li>"}
    </ul>
  </section>

  <section>
    <h2>Related Concepts</h2>
    <ul>
{related_html.rstrip() if related_html else "      <li>None linked yet.</li>"}
    </ul>
  </section>

  <section>
    <h2>Sources</h2>
    <ul>
{sources_html.rstrip()}
    </ul>
  </section>

  <div class="nav-footer">
    <a href="../explorer.html">Explorer</a> ·
    <a href="../docs.html#glossary">Docs Glossary</a> ·
    <a href="../docs.html#concepts">Concepts Table</a>
  </div>
</body>
</html>
"""
    out_path = os.path.join(CONCEPTS_DIR, f"{slug}.html")
    os.makedirs(CONCEPTS_DIR, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(page)
    print(f"  ✓ Generated concepts/{slug}.html")


def main():
    print("build_concepts.py — generating concept artifacts...")
    concepts = load_concepts()
    validate(concepts)
    generate_js(concepts)
    for c in concepts:
        generate_concept_page(c)
    print(f"\nDone. {len(concepts)} concepts processed.")


if __name__ == "__main__":
    main()
